<?php

    require_once '/var/www/external/services/mail/funciones_export.php';
    require_once '/var/www/external/services/mail/femexfut/querysFemexfut.php';

    $path_logo  = '/var/www/external/services/mail/femexfut/logoGA2.png';

if( isset($_GET['p']) && isset($_GET['f']) ) {
    $valor      = base64_decode( base64_decode($_GET['p']) ); 
    $estado     = 0;
    $query      = query($valor, $_GET['f'], $estado );

    if( isset( $_GET[ 'e' ] ) ) $estado = $_GET['e'];

    switch ( $valor ) {
        case 1: $tema = "PRIMERAS PLANAS"; $subtema = " ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break;
        case 2: $tema = "COLUMNAS POLITICAS";$subtema = " ";
                ArmaPdfColumnas($query,$tema,$subtema, $path_logo );
                break;
        case 3: $tema = "COLUMNAS FINANCIERAS ";$subtema=" ";
                ArmaPdfColumnas($query,$tema,$subtema, $path_logo );
                break;
        case 4: $tema = "CARTONES"; $subtema = " ";
                ArmaPdfColumnas($query,$tema,$subtema, $path_logo );
                break;
        case 5: $tema="FEMEXFUT - CDMX";$subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break;
        case 6: $tema=utf8_decode("FEMEXFUT - ESTADOS "); $subtema="  ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 7: $tema="SEL. NACIONAL - CDMX";$subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break;         
        case 8: $tema=utf8_decode("SEL. NACIONAL - ESTADOS" );$subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break;  
        case 9: $tema="AMERICA - CDMX";$subtema="";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 10:$tema=utf8_decode("AMERICA - ESTADOS" );$subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 11:$tema="ATLAS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 12:$tema=utf8_decode("ATLAS - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 13:$tema="CHIVAS - CDMX";$subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 14:$tema=utf8_decode("CHIVAS - ESTADOS" ); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 15:$tema="CRUZ AZUL - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 16:$tema=utf8_decode("CRUZ AZUL - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 17:$tema="DORADOS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 18:$tema=utf8_decode( "DORADOS - ESTADOS" ); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 19:$tema="GALLOS BLANCOS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 20:$tema=utf8_decode("GALLOS BLANCOS - ESTADOS" ); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 21:$tema="JAGUARES - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 22:$tema=utf8_decode("JAGUARES - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break;   
        case 23:$tema=utf8_decode("LEÓN - CDMX"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 24:$tema=utf8_decode("LEÓN - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 25:$tema="MONTERREY - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 26:$tema=utf8_decode("MONTERREY - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 27:$tema="MORELIA - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 28:$tema=utf8_decode("MORELIA - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 29:$tema="PACHUCA - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 30:$tema=utf8_decode("PACHUCA - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 31:$tema="PUEBLA - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 32:$tema=utf8_decode("PUEBLA - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 33:$tema="SAN LUIS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 34:$tema=utf8_decode("SAN LUIS - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 35:$tema="SANTOS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 36:$tema=utf8_decode("SANTOS - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 37:$tema="TIGRES - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 38:$tema=utf8_decode("TIGRES - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 39:$tema="TIJUANA - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 40:$tema=utf8_decode("TIJUANA - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 41:$tema="TOLUCA - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 42:$tema=utf8_decode("TOLUCA - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 43:$tema="UNAM - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 44:$tema=utf8_decode("UNAM - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 45:$tema="VERACRUZ - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 46:$tema=utf8_decode("VERACRUZ - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 47:$tema="VARIOS - CDMX"; $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
        case 48:$tema=utf8_decode("VARIOS - ESTADOS"); $subtema=" ";
                ArmaPdf($query,$tema,$subtema, $path_logo );
                break; 
    }
}